apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv0001 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany 
    #  nfs: 
    # path: /nfs-storage
    # server: 192.168.126.11 
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain

